using IBLTermocasa.Shared;
using IBLTermocasa.Products;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using IBLTermocasa.Permissions;
using IBLTermocasa.Subproducts;

namespace IBLTermocasa.Subproducts
{
    public class SubproductsAppService : SubproductsAppServiceBase, ISubproductsAppService
    {
        //<suite-custom-code-autogenerated>
        public SubproductsAppService(ISubproductRepository subproductRepository, SubproductManager subproductManager, IRepository<Product, Guid> productRepository)
            : base(subproductRepository, subproductManager, productRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}