using IBLTermocasa.Components;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace IBLTermocasa.Products
{
    public class ProductManager : ProductManagerBase
    {
        //<suite-custom-code-autogenerated>
        public ProductManager(IProductRepository productRepository,
        IRepository<Component, Guid> componentRepository)
            : base(productRepository, componentRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}