using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace IBLTermocasa.Products
{
    public class Product : ProductBase
    {
        //<suite-custom-code-autogenerated>
        protected Product()
        {

        }

        public Product(Guid id, string code, string name, bool isAssembled, bool isInternal, string? description = null)
            : base(id, code, name, isAssembled, isInternal, description)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}