using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace IBLTermocasa.Contacts
{
    public class Contact : ContactBase
    {
        //<suite-custom-code-autogenerated>
        protected Contact()
        {

        }

        public Contact(Guid id, string name, string surname, DateTime birthDate, string? title = null, string? confidentialName = null, string? jobRole = null, string? mailInfo = null, string? phoneInfo = null, string? socialInfo = null, string? addressInfo = null, string? tag = null, string? notes = null)
            : base(id, name, surname, birthDate, title, confidentialName, jobRole, mailInfo, phoneInfo, socialInfo, addressInfo, tag, notes)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}