using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace IBLTermocasa.Contacts
{
    public class ContactManager : ContactManagerBase
    {
        //<suite-custom-code-autogenerated>
        public ContactManager(IContactRepository contactRepository)
            : base(contactRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}