using IBLTermocasa.Types;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace IBLTermocasa.Materials
{
    public class MaterialManager : MaterialManagerBase
    {
        //<suite-custom-code-autogenerated>
        public MaterialManager(IMaterialRepository materialRepository)
            : base(materialRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}