using IBLTermocasa.Shared;
using IBLTermocasa.Materials;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using IBLTermocasa.Permissions;
using IBLTermocasa.ComponentItems;

namespace IBLTermocasa.ComponentItems
{
    public class ComponentItemsAppService : ComponentItemsAppServiceBase, IComponentItemsAppService
    {
        //<suite-custom-code-autogenerated>
        public ComponentItemsAppService(IComponentItemRepository componentItemRepository, ComponentItemManager componentItemManager, IRepository<Material, Guid> materialRepository)
            : base(componentItemRepository, componentItemManager, materialRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}