using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace IBLTermocasa.Components
{
    public class Component : ComponentBase
    {
        //<suite-custom-code-autogenerated>
        protected Component()
        {

        }

        public Component(Guid id, string name)
            : base(id, name)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}