using IBLTermocasa.Materials;
using IBLTermocasa.Materials;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace IBLTermocasa.Components
{
    public class ComponentManager : ComponentManagerBase
    {
        //<suite-custom-code-autogenerated>
        public ComponentManager(IComponentRepository componentRepository)
            : base(componentRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}