using IBLTermocasa.Products;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace IBLTermocasa.Subproducts
{
    public class Subproduct : SubproductBase
    {
        //<suite-custom-code-autogenerated>
        protected Subproduct()
        {

        }

        public Subproduct(Guid id, Guid productId, Guid? singleProductId, int order, string name, bool isSingleProduct, bool mandatory)
            : base(id, productId, singleProductId, order, name, isSingleProduct, mandatory)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}