using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace IBLTermocasa.Subproducts
{
    public class SubproductManager : SubproductManagerBase
    {
        //<suite-custom-code-autogenerated>
        public SubproductManager(ISubproductRepository subproductRepository)
            : base(subproductRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}