# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy TCP API UI

on:
  workflow_dispatch:

jobs:
  build-apihost:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true
      
      - name: Build with dotnet
        run: dotnet build --configuration Release

#      - name: Run migrations
#        run: dotnet run -- "${{ secrets.CONNECTION_STRING }}"
#        working-directory: ./src/IBLTermocasa.DbMigrator 

      - name: dotnet publish apihost
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/apihost
        working-directory: ./src/IBLTermocasa.HttpApi.Host 

      - name: Upload artifact for apihost
        uses: actions/upload-artifact@v4
        with:
          name: apihost
          path: ${{env.DOTNET_ROOT}}/apihost

  deploy-apihost:
    runs-on: ubuntu-latest
    needs: build-apihost
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from apihost
        uses: actions/download-artifact@v4
        with:
          name: apihost
          path: ./apihost

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_808D774C976F428B88AE38F84CA45C52 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5C231986D6DF48C59832D4985333EB03 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1B7FC95956E2429C8C27936FA10FE44B }}
          
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'api-tcp'
          slot-name: 'Production'
          package: .

#  build-deploy-frontend:
#    runs-on: ubuntu-latest
#    needs: 
#      - deploy-apihost
#    name: Build and Deploy Job
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          submodules: true
#      - name: Build And Deploy
#        id: builddeploy
#        uses: Azure/static-web-apps-deploy@v1
#        with:
#          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_WAVE_005731103 }} 
#          repo_token: ${{ secrets.GITHUB_TOKEN }} 
#          action: "upload"
#          app_location: "src/IBLTermocasa.Blazor" 
#          api_location: "" 
#          output_location: "wwwroot" 
