# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: TCP API Build and deploy

on:
  workflow_dispatch:
    inputs:
      azure_environment:
        description: 'Azure Environment'
        required: true
        type: choice
        options:
          - 'Production'
          - 'Staging'
          - 'Development'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Publish with dotnet Apihost
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/apihost /p:EnvironmentName=Production
        working-directory: ./src/IBLTermocasa.HttpApi.Host
      
      - name: Upload artifact for Apihost
        uses: actions/upload-artifact@v4
        with:
          name: apihost
          path: ${{env.DOTNET_ROOT}}/apihost

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Set Environment Variables
        env: 
          azure_environment: ${{ github.event.inputs.azure_environment }}
          prod_client_id: ${{ secrets.PROD_API_CLIENT_ID }}
          prod_tenant_id: ${{ secrets.PROD_API_TENANT_ID }}
          prod_subscription_id: ${{ secrets.PROD_API_SUBSCRIPTION_ID }}
          stg_client_id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_808D774C976F428B88AE38F84CA45C52 }}
          stg_tenant_id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5C231986D6DF48C59832D4985333EB03 }}
          stg_subscription_id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1B7FC95956E2429C8C27936FA10FE44B }}
          dev_client_id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_808D774C976F428B88AE38F84CA45C52 }}
          dev_tenant_id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5C231986D6DF48C59832D4985333EB03 }}
          dev_subscription_id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1B7FC95956E2429C8C27936FA10FE44B }}
        run: |
          echo "Selected Azure Environment: ${{ github.event.inputs.azure_environment }}"
          case ${{ github.event.inputs.azure_environment }} in
            Production)
              echo "CLIENT_ID=${{ env.prod_client_id }}" >> $GITHUB_ENV
              echo "TENANT_ID=${{ env.prod_tenant_id }}" >> $GITHUB_ENV
              echo "SUBSCRIPTION_ID=${{ env.prod_subscription_id }}" >> $GITHUB_ENV
              echo "APP_NAME=api-tcp" >> $GITHUB_ENV
              ;;
            Staging)
              echo "CLIENT_ID=${{ env.stg_client_id }}" >> $GITHUB_ENV
              echo "TENANT_ID=${{ env.stg_tenant_id }}" >> $GITHUB_ENV
              echo "SUBSCRIPTION_ID=${{ env.stg_subscription_id }}" >> $GITHUB_ENV
              echo "APP_NAME=api-tcp" >> $GITHUB_ENV
              ;;
            Development)
              echo "CLIENT_ID=${{ env.dev_client_id }}" >> $GITHUB_ENV
              echo "TENANT_ID=${{ env.dev_tenant_id }}" >> $GITHUB_ENV
              echo "SUBSCRIPTION_ID=${{ env.dev_subscription_id }}" >> $GITHUB_ENV
              echo "APP_NAME='api-tcp'" >> $GITHUB_ENV
              ;;
            *)
              echo "Unknown environment: ${{ github.event.inputs.azure_environment }}"
              exit 1
              ;;
          esac
          echo "<<<<<<<<<<<<<<<<ENV>>>>>>>>>>>>>>>>"
          echo "$GITHUB_ENV"
      - name: Download artifact from Apihost
        uses: actions/download-artifact@v4
        with:
          name: apihost
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ env.CLIENT_ID }}
          tenant-id: ${{ env.TENANT_ID }}
          subscription-id: ${{ env.SUBSCRIPTION_ID }}

      - name: Deploy to Azure Apihost [api-tcp]
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: '${{ env.APP_NAME }}'
          slot-name: 'Production' # Only Production slot is supported
          package: .
          