# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: TCP Auth Build and deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Publish with dotnet AuthServer
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/auth  /p:EnvironmentName=Production
        working-directory: ./src/IBLTermocasa.AuthServer

      - name: Generate certificate for HTTPS
        run:  dotnet dev-certs https -v -ep openiddict.pfx -p b40d4664-8e26-4172-b6a8-6a8c8de03ab7 -t

      - name: Copy certificate to auth folder
        run: cp openiddict.pfx ${{env.DOTNET_ROOT}}/auth

      - name: Upload artifact for AuthServer
        uses: actions/upload-artifact@v3
        with:
          name: auth
          path: ${{env.DOTNET_ROOT}}/auth

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from AuthServer
        uses: actions/download-artifact@v3
        with:
          name: auth

      - name: Deploy to Azure AuthServer [auth-tcp]
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'auth-tcp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_97187E9F86E747899B377F98F16B8A02 }}
          package: .
