# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Web App - auth-tcp

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install ABP CLI
        run: |
          dotnet tool install -g Volo.Abp.Cli
          abp install-libs
        shell: bash
        
      - name: Build with dotnet
        run: dotnet build --configuration Release
        working-directory: ./src/IBLTermocasa.AuthServer

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
        working-directory: ./src/IBLTermocasa.AuthServer

      - name: Generate certificate for HTTPS
        run:  dotnet dev-certs https -v -ep openiddict.pfx -p b40d4664-8e26-4172-b6a8-6a8c8de03ab7 -t

      - name: Copy certificate to auth folder
        run: cp openiddict.pfx ${{env.DOTNET_ROOT}}/myapp
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7CAE23D86BC648909C1050DA39AABE40 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_100AEEE2E767407BB9A7C61F67F2E502 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E20C1E4DE3CA4CA8A8C2E8B53FA44AEF }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'auth-tcp'
          slot-name: 'Production'
          package: .
          