using IBLTermocasa.Materials;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace IBLTermocasa.ComponentItems
{
    public class ComponentItem : ComponentItemBase
    {
        //<suite-custom-code-autogenerated>
        protected ComponentItem()
        {

        }

        public ComponentItem(Guid id, Guid componentId, Guid materialId, bool isDefault)
            : base(id, componentId, materialId, isDefault)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}