using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace IBLTermocasa.ComponentItems
{
    public class ComponentItemManager : ComponentItemManagerBase
    {
        //<suite-custom-code-autogenerated>
        public ComponentItemManager(IComponentItemRepository componentItemRepository)
            : base(componentItemRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}